openapi: 3.0.0
info:
  title: Feature Toggle API - Instagram Links Rename
  version: 1.1.0
  description: API contract for feature toggle with renamed instagram_links feature

paths:
  /api/wedding/config/features:
    put:
      summary: Toggle wedding feature
      description: Enable or disable a wedding feature including the renamed instagram_links
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - featureName
                - isEnabled
              properties:
                featureName:
                  type: string
                  enum:
                    - love_story
                    - rsvp
                    - gallery
                    - prewedding_videos
                    - faqs
                    - dress_code
                    - instagram_links
                    - wishes
                  description: Name of the feature to toggle (instagram_links renamed from instagram_link)
                isEnabled:
                  type: boolean
                  description: Whether to enable or disable the feature
              example:
                featureName: "instagram_links"
                isEnabled: true
      responses:
        '200':
          description: Feature toggle updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      featureName:
                        type: string
                        example: "instagram_links"
                      isEnabled:
                        type: boolean
                        example: true
        '400':
          description: Invalid feature name or request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid feature name"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Unauthorized"

components:
  schemas:
    FeatureToggle:
      type: object
      properties:
        id:
          type: string
          description: Unique toggle ID
        weddingConfigId:
          type: string
          description: Associated wedding configuration ID
        featureName:
          type: string
          enum:
            - love_story
            - rsvp
            - gallery
            - prewedding_videos
            - faqs
            - dress_code
            - instagram_links
            - wishes
          description: Name of the feature
        isEnabled:
          type: boolean
          description: Whether the feature is enabled
        createdAt:
          type: integer
          description: Creation timestamp
        updatedAt:
          type: integer
          description: Last update timestamp
      example:
        id: "ftr_abc123"
        weddingConfigId: "clxyz123abc"
        featureName: "instagram_links"
        isEnabled: true
        createdAt: 1704067200000
        updatedAt: 1718409600000
