-- Turso Database Backup
-- Generated: 2025-10-04T20:57:47.866Z
-- Database: libsql://wedding-invitation-karelkarunia.turso.io


-- Table: guests
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (2, 249, 'Graciel Rivkah B. T.', 11, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (3, 250, 'Mega S. T.', 11, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (4, 251, 'Jacklin Marselau', 11, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (6, 253, 'Kathleen M. B.', 11, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (8, 255, 'Ruben Adhitama', 11, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (14, 291, 'Ignatius Jevon', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (15, 292, 'Sean Gerry S', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (17, 293, 'Jeremy Alvian', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (18, 294, 'David C. H.', 3, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (19, 294, 'David C. H. +1', 3, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (20, 295, 'Luiz Juan F.', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (23, 297, 'Felicia C. Y.', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (24, 300, 'Eric P. A.', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (25, 301, 'Natasya Maria D.', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (26, 302, 'Monica H. W.', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (27, 303, 'Jessica Santoso', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (28, 303, 'Jessica Santoso +1', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (31, 306, 'Felita Cahya', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (32, 307, 'Virla Sandyka', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (33, 307, 'Virla Sandyka +1', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (34, 308, 'Teddy S. W.', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (35, 310, 'Ferdian N.', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (36, 311, 'Andreas Halim', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (39, 313, 'Debora N.', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (40, 313, 'Debora N. +1', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (41, 314, 'Anastasya Dwita', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (42, 314, 'Anastasya Dwita +1', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (43, 315, 'Wynne Kusuma', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (44, 315, 'Wynne Kusuma +1', 7, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (47, 322, 'Aurelius Ansel', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (48, 323, 'Hartono Diposubagio', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (49, 323, 'Hartono Diposubagio +1', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (50, 324, 'Lim Ferdy Iskandar', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (51, 324, 'Lim Ferdy Iskandar +1', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (56, 333, 'Richard S. T.', 3, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (57, 333, 'Richard S. T. +1', 3, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (58, 335, 'Diandra Ariel', 3, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (59, 335, 'Diandra Ariel +1', 3, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (60, 336, 'Leonardo Tandya', 3, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (61, 336, 'Leonardo Tandya +1', 3, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (66, 339, 'The Tiang  Sioe and Ong Sien Lian', 18, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (73, 342, 'Albert and family', 18, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (74, 342, 'Albert and family +1', 18, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (75, 342, 'Albert and family +2', 18, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (76, 342, 'Albert and family +3', 18, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (77, 342, 'Albert and family +4', 18, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (78, 343, 'Adi', 18, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (79, 344, 'The Tiang Tjoe', 18, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (81, 346, 'Henry Krisnawan', 27, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (82, 346, 'Henry Krisnawan +1', 27, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (83, 346, 'Henry Krisnawan +2', 27, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (84, 348, 'Handriyana Hardha', 22, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (85, 348, 'Handriyana Hardha +1', 22, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (86, 349, 'Erik', 22, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (87, 349, 'Erik +1', 22, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (88, 350, 'Reymond', 22, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (89, 350, 'Reymond +1', 22, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (90, 351, 'Handhaka Hardha', 22, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (91, 351, 'Handhaka Hardha +1', 22, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (92, 352, 'Wibowo Sastro Utomo', 27, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (93, 353, 'Patompo Sangidi', 23, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (94, 353, 'Patompo Sangidi +1', 23, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (100, 358, 'Iwan Suteja', 23, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (101, 358, 'Iwan Suteja +1', 23, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (102, 359, 'Ershandy Hermanto', 23, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (103, 359, 'Ershandy Hermanto +1', 23, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (104, 359, 'Ershandy Hermanto +2', 23, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (107, 360, 'Natalia', 23, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (117, 365, 'Liem Sing Hauw', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (120, 367, 'Yessy', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (121, 368, 'Maya', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (122, 368, 'Maya +1', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (123, 369, 'Rudy Widjanarso', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (124, 369, 'Rudy Widjanarso +1', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (131, 373, 'Johnny', 41, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (132, 373, 'Johnny +1', 41, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (133, 373, 'Johnny +2', 41, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (134, 374, 'Willy Ananta', 41, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (135, 374, 'Willy Ananta +1', 41, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (136, 375, 'Mario', 41, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (137, 375, 'Mario +1', 41, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (138, 376, 'Nugroho', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (139, 376, 'Nugroho +1', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (140, 378, 'Mita Kristanto', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (141, 378, 'Mita Kristanto +1', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (142, 378, 'Mita Kristanto +2', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (143, 378, 'Mita Kristanto +3', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (144, 379, 'Hadi Suryono', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (145, 379, 'Hadi Suryono +1', 14, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (146, 380, 'Adrian Teja', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (147, 380, 'Adrian Teja +1', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (148, 380, 'Adrian Teja +2', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (149, 380, 'Adrian Teja +3', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (150, 381, 'Aditya Teja', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (155, 383, 'Sik Liat', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (157, 384, 'Ivan', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (158, 384, 'Ivan +1', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (159, 385, 'Bwe Fong', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (160, 386, 'Mee Man', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (161, 386, 'Mee Man +1', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (162, 387, 'Hong Chu and Family', 27, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (163, 388, 'Hong Loan and Family', 27, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (168, 390, 'Sen Tjong and Family', 27, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (169, 390, 'Sen Tjong and Family +1', 27, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (170, 390, 'Sen Tjong and Family +2', 27, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (171, 391, 'Go Nancy Yuliawati', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (172, 391, 'Go Nancy Yuliawati +1', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (173, 392, 'Michael Gunawan', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (174, 392, 'Michael Gunawan +1', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (175, 392, 'Michael Gunawan +2', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (176, 392, 'Michael Gunawan +3', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (180, 395, 'Yasinta', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (198, 406, 'Ellyati Djohari', 28, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (199, 406, 'Ellyati Djohari +1', 28, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (205, 413, 'Hundarto Santoso', 28, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (206, 413, 'Hundarto Santoso +1', 28, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (207, 414, 'Sandra Santoso', 28, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (208, 414, 'Sandra Santoso +1', 28, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (209, 415, 'Heru Santoso', 28, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (210, 415, 'Heru Santoso +1', 28, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (211, 417, 'Yen2', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (212, 417, 'Yen2 +1', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (213, 419, 'Vania', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (218, 423, 'Michael Wong', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (219, 423, 'Michael Wong +1', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (220, 423, 'Michael wong +2', 16, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (225, 426, 'Beny Sugiharto', 48, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (226, 426, 'Beny Sugiharto +1', 48, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (227, 427, 'Hanny Sugiharto', 48, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (228, 427, 'Hanny Sugiharto +1', 48, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (229, 428, 'Djie Kian Sin', 48, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (230, 428, 'Djie Kian Sin +1', 48, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (231, 429, 'Hendra Kurniawan Tjipto', 13, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (232, 429, 'Hendra Kurniawan Tjipto +1', 13, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (233, 430, 'Benny - Yenny', 13, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (234, 430, 'Benny +1', 13, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (235, 431, 'Kurtandi', 13, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (236, 431, 'Kurtandi +1', 13, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (237, 432, 'Surijati', 13, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (238, 433, 'Henny Ling', 37, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (239, 434, 'Siane', 37, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (240, 435, 'Lenny', 13, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (241, 435, 'Lenny +1', 13, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (242, 436, 'Yanti', 13, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (243, 437, 'Irwan Hartono', 37, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (244, 437, 'Irwan Hartono +1', 37, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (245, 438, 'Tatik', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (246, 438, 'Tatik +1', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (247, 439, 'Dwi', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (248, 440, 'Solikin', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (249, 441, 'Iqli', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (251, 445, 'Abi', 35, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (252, 446, 'Amin', 25, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (253, 447, 'Oei Bing Hauw', 35, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (254, 447, 'Oei Bing Hauw +1', 35, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (255, 448, 'Bambang', 35, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (256, 449, 'Bejo', 36, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (261, 453, 'Hian Bing', 34, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (262, 453, 'Hian Bing +1', 34, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (263, 454, 'Hian Tjiong', 25, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (264, 455, 'James', 34, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (265, 455, 'James +1', 34, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (266, 456, 'Ka Diong', 25, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (269, 458, 'Lam Hay', 34, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (270, 458, 'Lam Hay +1', 34, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (271, 459, 'Lolok', 34, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (272, 459, 'Lolok +1', 34, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (273, 460, 'Maxi', 34, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (274, 460, 'Maxi +1', 34, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (275, 461, 'Robert Gunawan', 25, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (276, 462, 'Pek Ho', 33, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (277, 462, 'Pek Ho +1', 33, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (278, 463, 'Ping Liang', 33, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (279, 463, 'Ping Liang +1', 33, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (280, 464, 'Sek Go', 33, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (281, 464, 'Sek Go +1', 33, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (282, 465, 'Sik An', 33, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (283, 465, 'Sik An +1', 33, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (284, 466, 'Sing Kwok', 25, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (285, 467, 'Nono - Linda', 25, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (286, 467, 'Nono +1', 25, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (287, 468, 'Siok Ming', 33, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (290, 470, 'Tik Djien', 25, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (291, 471, 'Tony', 25, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (292, 472, 'Johnny', 25, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (293, 473, 'Agung', 26, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (294, 474, 'David', 32, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (295, 474, 'David +1', 32, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (296, 475, 'Ferry', 26, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (297, 475, 'Ferry +1', 26, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (298, 476, 'Harsono', 26, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (299, 477, 'Hengky', 32, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (301, 478, 'Iwan', 47, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (302, 478, 'Iwan +1', 47, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (303, 479, 'Jeffry', 31, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (304, 479, 'Jeffry +1', 31, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (305, 480, 'Juned', 31, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (306, 481, 'Marcus', 31, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (307, 481, 'Marcus +1', 31, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (308, 482, 'Victor', 31, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (309, 483, 'Widodo', 26, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (310, 483, 'Widodo +1', 26, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (311, 484, 'Yung2', 30, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (312, 484, 'Yung2 +1', 30, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (313, 485, 'Rudy', 26, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (314, 485, 'Rudy +1', 26, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (318, 488, 'Yen2', 31, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (319, 489, 'Andy Sentosa/Sinta', 32, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (320, 489, 'Andy Sentosa/Sinta +1', 32, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (321, 490, 'Brata Perdana', 30, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (322, 490, 'Brata Perdana +1', 30, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (323, 491, 'Tri', 26, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (324, 491, 'Tri +1', 26, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (325, 492, 'Anto', 30, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (326, 492, 'Anto +1', 30, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (327, 493, 'Herman', 47, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (328, 493, 'Herman +1', 47, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (329, 494, 'Hendi', 31, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (330, 495, 'Liman', 31, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (331, 495, 'Liman +1', 31, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (334, 497, 'Iwan yasmine', 30, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (335, 497, 'Iwan yasmine +1', 30, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (336, 498, 'Hoo Tay Kwie', 36, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (337, 498, 'Hoo Tay Kwie +1', 36, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (340, 500, 'Bing2 - lenny', 36, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (341, 500, 'Bing2 +1', 36, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (342, 501, 'Nive', 36, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (343, 502, 'Robert Juwana', 30, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (344, 502, 'Robert Juwana +1', 30, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (345, 503, 'Priono', 36, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (346, 503, 'Priono +1', 36, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (347, 504, 'Iswan Ming', 36, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (348, 504, 'Iswan Ming +1', 36, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (349, 505, 'Yohanes Nugroho', 32, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (351, 506, 'Imelda', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (352, 506, 'Imelda +1', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (353, 508, 'Joen', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (354, 508, 'Joen +1', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (355, 509, 'Wenata', 42, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (356, 509, 'Wenata +1', 42, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (357, 510, 'Christo', 42, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (358, 510, 'Christo +1', 42, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (361, 512, 'Stephan Antonius', 37, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (362, 513, 'Widi Rendi', 37, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (363, 513, 'Widi Rendi +1', 37, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (364, 514, 'Yulius Wibisono', 37, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (365, 514, 'Yulius Wibisono +1', 37, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (368, 517, 'Antony', 42, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (369, 517, 'Antony +1', 42, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (370, 518, 'Nono - Maya', 42, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (371, 518, 'Nono +1', 42, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (372, 519, 'Djoenny Trihandajani', 42, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (373, 519, 'Djoenny Trihandajani +1', 42, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (375, 522, 'Bebe', 48, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (376, 522, 'Bebe +1', 48, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (377, 522, 'Bebe +2', 48, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (378, 523, 'Suhardjo', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (379, 523, 'Suhardjo +1', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (380, 524, 'Hendro Luhur', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (381, 524, 'Hendro Luhur +1', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (382, 525, 'Meliana', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (383, 526, 'Wiwien Susiana', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (384, 527, 'Kartika Kumala', 32, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (386, 529, 'Yongky', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (387, 529, 'Yongky +1', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (388, 531, 'Asril', 39, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (389, 531, 'Asril +1', 39, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (390, 532, 'Bambang Mul', 39, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (391, 532, 'Bambang Mul +1', 39, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (392, 533, 'Dewi', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (393, 534, 'Foundy', 39, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (394, 534, 'Foundy +1', 39, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (395, 535, 'Hadi', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (396, 535, 'Hadi +1', 24, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (397, 536, 'Hernanto', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (398, 536, 'Hernanto +1', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (399, 537, 'Imron', 39, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (400, 537, 'Imron +1', 39, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (401, 538, 'Ivan Siok Ming', 33, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (402, 539, 'Jusri', 39, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (403, 539, 'Jusri +1', 39, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (404, 540, 'Slamet', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (405, 540, 'Slamet +1', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (406, 541, 'Tommy', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (407, 541, 'Tommy +1', 40, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (408, 542, 'Heri Sin', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (415, 548, 'Aditya Wilopo', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (416, 548, 'Aditya Wilopo +1', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (417, 550, 'Edwin Santosa', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (418, 550, 'Edwin Santosa +1', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (419, 551, 'Budi Hartono', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (420, 551, 'Budi Hartono +1', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (421, 552, 'Karel and Fam', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (422, 552, 'Kucin', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (423, 552, 'Cuung', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (424, 552, 'Papa', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (425, 552, 'Mama', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (426, 552, 'Cece', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (427, 552, 'Koko', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (428, 552, 'Akong', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (429, 552, 'Ama', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (430, 554, 'Sab and fam', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (431, 554, 'Tata', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (432, 554, 'Dad', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (433, 554, 'Mami', 10, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (434, 554, 'Gab', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (437, 557, 'Ang Wie Hay', 37, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (438, 718, 'Tet Sen', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (439, 718, 'Tet Sen +1', 17, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (440, 719, 'Hidayat', 47, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (441, 721, 'Ami', 35, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (442, 721, 'Ami +1', 35, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (454, 614, 'William', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (455, 614, 'William +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (456, 614, 'William +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (457, 349, 'Erik +2', 22, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (458, 349, 'Erik +3', 22, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (459, 612, 'Tommy', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (461, 715, 'Hannie Anwari and Irmawaty', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (464, 639, 'Lay Nyit Fa and Tjandra Widjaja', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (465, 639, 'Lay Nyit Fa and Tjandra Widjaja +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (466, 638, 'Wilbert Miquel', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (467, 638, 'Wilbert Miquel +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (468, 571, 'Daniel Djumali and Listyawati', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (469, 571, 'Daniel Djumali and Listyawati +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (470, 720, 'Michael Wong', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (471, 720, 'Ako', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (472, 720, 'Tammy', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (473, 636, 'Suwendi Firmanto', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (474, 717, 'Evanpin Budiman', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (475, 717, 'Evanpin Budiman +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (476, 603, 'Phang Tjong Mio', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (477, 603, 'Phang Tjong Mio +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (478, 608, 'Siska', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (479, 635, 'Suryadi Firmanto', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (480, 384, 'Ivan +2', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (481, 384, 'Ivan +3', 15, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (482, 729, 'Elgin Gavriel', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (483, 729, 'Elgin Gavriel +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (484, 728, 'Egan Gavriel', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (485, 728, 'Egan Gavriel +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (486, 732, 'Martono', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (487, 732, 'Martono +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (535, 704, 'Nicole and Jason', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (536, 704, 'Nicole and Jason +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (537, 678, 'Sharon Gabrielle', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (538, 678, 'Sharon Gabrielle +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (539, 542, 'Heri Sin +1', 45, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (540, 733, 'Hendri Irawan (Afong)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (541, 733, 'Hendri Irawan (Afong) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (542, 734, 'Ernie Martsiswati', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (543, 572, 'Danny Sudirman (Erika)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (544, 572, 'Danny Sudirman (Erika) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (545, 659, 'Karsan Lakaban', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (546, 659, 'Karsan Lakaban +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (547, 625, 'Samuel Tirtanadi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (548, 625, 'Samuel Tirtanadi +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (549, 715, 'Hannie Anwari and Irmawaty +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (550, 715, 'Hannie Anwari and Irmawaty +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (551, 560, 'Andreas S. Tjendana', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (552, 560, 'Andreas S. Tjendana +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (553, 642, 'Pdt. Philip Cia', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (554, 642, 'Pdt. Philip Cia +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (555, 686, 'Teddy Vinaya', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (556, 686, 'Teddy Vinaya +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (557, 584, 'Gidiyon', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (558, 584, 'Gidiyon +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (559, 584, 'Gidiyon +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (560, 584, 'Gidiyon +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (561, 735, 'Liem Kian Soen', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (562, 735, 'Liem Kian Soen +1', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (563, 735, 'Liem Kian Soen +2', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (564, 735, 'Liem Kian Soen +3', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (565, 736, 'Ayu', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (566, 736, 'Ayu +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (569, 738, 'Anggi and Arief', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (575, 741, 'Michelle', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (576, 741, 'Michelle +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (583, 745, 'Joey', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (584, 745, 'Joey +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (589, 748, 'Wilsen', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (590, 748, 'Wilsen +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (591, 749, 'Daniel', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (592, 749, 'Daniel +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (623, 623, 'Jonathan Kurniawan (Nana)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (624, 623, 'Jonathan Kurniawan (Nana) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (625, 623, 'Jonathan Kurniawan (Nana) +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (626, 623, 'Jonathan Kurniawan (Nana) +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (627, 654, 'Pdt. Djab Johanes', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (628, 654, 'Pdt. Djab Johanes +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (629, 660, 'Vic. Murniaty Santoso', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (630, 660, 'Vic. Murniaty Santoso +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (634, 561, 'Andrian Therianto', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (635, 561, 'Andrian Therianto +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (636, 561, 'Andrian Therianto +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (639, 681, 'Jeremy Arden', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (640, 681, 'Jeremy Arden +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (641, 586, 'Indriani Salim', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (642, 767, 'Bukhiang (Aling)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (643, 767, 'Bukhiang (Aling) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (644, 768, 'Tony (Atung)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (645, 768, 'Tony (Atung) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (646, 769, 'Rudy (Akui)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (647, 769, 'Rudy (Akui) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (648, 770, 'Hengki', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (649, 770, 'Hengki +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (650, 771, 'Didi (Akhun)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (651, 772, 'Jenni', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (652, 772, 'Jenni +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (653, 773, 'Tina', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (654, 774, 'Fu Lie Fung', 55, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (655, 775, 'Amiang', 55, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (656, 776, 'Atong', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (657, 777, 'Lim Ju Chai', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (658, 777, 'Lim Ju Chai +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (659, 778, 'Lim Sie Khiang', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (660, 778, 'Lim Sie Khiang +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (661, 779, 'Cu Siat Jam', 55, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (662, 780, 'Abi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (663, 781, 'Akhun', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (664, 781, 'Akhun +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (669, 783, 'Fu Lung Hin', 55, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (671, 784, 'Vincent', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (672, 784, 'Vincent +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (673, 785, 'Lim Siau Jan', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (674, 786, 'Edwin Kurniawan', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (675, 786, 'Edwin Kurniawan +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (676, 787, 'Fu Kwet Hin', 55, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (679, 789, 'Phang A Khiang', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (680, 789, 'Phang A Khiang +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (681, 790, 'Tifen', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (682, 790, 'Tifen +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (683, 791, 'Khou Song Nam', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (684, 791, 'Khou Song Nam +1', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (685, 792, 'Khou Sok Miang', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (686, 793, 'Athur', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (687, 793, 'Athur +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (688, 794, 'Khou Liang Weng', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (689, 794, 'Khou Liang Weng +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (690, 795, 'Tan Hui Kiang', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (691, 796, 'Herry', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (692, 796, 'Herry +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (693, 798, 'Liu Khun Sen', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (694, 798, 'Liu Khun Sen +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (695, 799, 'Ahiap', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (696, 799, 'Ahiap +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (697, 800, 'Ali, Ahuang & Aleng', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (698, 800, 'Ali, Ahuang & Aleng +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (699, 800, 'Ali, Ahuang & Aleng +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (700, 801, 'Sung Tet Kui', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (701, 801, 'Sung Tet Kui +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (702, 802, 'Bun Jiu Ciu', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (703, 803, 'Aphing', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (704, 803, 'Aphing +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (705, 804, 'Achoi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (706, 804, 'Achoi +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (707, 805, 'Samfung', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (708, 806, 'Mu Kim Man', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (710, 807, 'Thai Pin', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (711, 807, 'Thai Pin +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (712, 632, 'Akong (Johanes Firmanto)', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (726, 396, 'Rudy Gunawan', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (727, 396, 'Rudy Gunawan +1', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (728, 396, 'Rudy Gunawan +2', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (729, 396, 'Rudy Gunawan +3', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (730, 396, 'Rudy Gunawan +4', 43, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (731, 363, 'Pudjiono and The Hwie Hian', 23, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (734, 363, 'Pudjiono and The Hwie Hian +1', 23, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (735, 450, 'Tjwan Bing', 35, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (736, 450, 'Tjwan Bing +1', 35, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (741, 719, 'Hidayat +1', 47, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (742, 493, 'Herman +2', 47, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (743, 493, 'Herman +3', 47, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (744, 493, 'Herman +4', 47, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (745, 493, 'Herman +5', 11, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (746, 389, 'Fung Jing and Family', 27, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (752, 589, 'Jeffrey Prasetio and Family', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (753, 589, 'Jeffrey Prasetio and Family +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (754, 589, 'Jeffrey Prasetio and Family +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (755, 589, 'Jeffrey Prasetio and Family +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (756, 690, 'Ruth Medyani', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (757, 690, 'Ruth Medyani +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (758, 670, 'Daniel Savalas', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (759, 670, 'Daniel Savalas +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (760, 457, 'Kian Hok', 35, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (761, 457, 'Kian Hok +1', 35, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (762, 648, 'Harmin S.', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (763, 648, 'Harmin S. +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (764, 648, 'Harmin S. +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (765, 648, 'Harmin S. +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (766, 633, 'Ama (Heng Gek Kian)', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (767, 605, 'Rudy Harjanto (Irma)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (768, 674, 'Felix Octavio', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (769, 474, 'David +2', 32, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (771, 709, 'Wildan and Mervianty', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (772, 709, 'Wildan and Mervianty +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (773, 808, 'Cong Kit Phin', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (774, 808, 'Cong Kit Phin +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (775, 682, 'Ivan Then', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (776, 682, 'Ivan Then +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (779, 406, 'Ellyati Djohari +2', 28, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (780, 406, 'Ellyati Djohari +3', 28, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (785, 811, 'Kurniawan Firmanto (Ciloi)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (786, 811, 'Kurniawan Firmanto (Ciloi) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (789, 813, 'Handoyo', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (790, 813, 'Handoyo +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (791, 814, 'Hankim', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (792, 814, 'Hankim +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (793, 815, 'Yantono', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (794, 815, 'Yantono +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (795, 816, 'Neo Lenny', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (796, 817, 'Andi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (798, 818, 'Fakun', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (799, 818, 'Fakun +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (802, 820, 'Rina (Kiok Eng) & Mei Ing', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (803, 820, 'Rina (Kiok Eng) & Mei Ing +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (804, 821, 'Suhendra', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (805, 822, 'CE IE (Sumoy)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (806, 822, 'CE IE (Sumoy) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (807, 823, 'Irwan Lie', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (808, 823, 'Irwan Lie +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (809, 824, 'Fransiskus', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (810, 824, 'Fransiskus +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (811, 825, 'Theresia L. (Nini)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (812, 826, 'Lih Mainah (Eli)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (813, 827, 'Bun Haryati', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (814, 828, 'Dick Roy (Eva)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (815, 828, 'Dick Roy (Eva) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (816, 548, 'Aditya Wilopo +2', 8, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (817, 722, 'Robby', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (818, 722, 'Robby +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (819, 829, 'Endi Budiono and Family', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (820, 829, 'Endi Budiono and Family +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (821, 829, 'Endi Budiono and Family +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (822, 830, 'Rendy and Family +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (823, 830, 'Rendy and Family', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (824, 830, 'Rendy and Family +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (828, 611, 'Tjin San Bin', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (829, 611, 'Tjin San Bin +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (831, 714, 'Kwee Moy Lie and Moy Ling', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (832, 714, 'Kwee Moy Lie and Moy Ling +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (833, 806, 'Mu Kim Man +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (834, 618, 'Fredy Suryanto (Magda)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (835, 618, 'Fredy Suryanto (Magda) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (836, 618, 'Fredy Suryanto (Magda) +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (837, 618, 'Fredy Suryanto (Magda) +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (838, 640, 'Huina Loekman', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (839, 617, 'Thoeng Kong Fa', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (840, 617, 'Thoeng Kong Fa +1', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (841, 671, 'Elbert Fernando', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (842, 671, 'Elbert Fernando +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (844, 831, 'Bobby', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (845, 831, 'Bobby +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (846, 832, 'Tio Hiap Ngi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (847, 832, 'Tio Hiap Ngi +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (848, 604, 'Rina Anggriani', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (849, 627, 'Esty', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (850, 426, 'Beny Sugiharto +2', 48, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (851, 634, 'Muliadi Firmanto', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (852, 634, 'Kimkim', 52, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (853, 558, 'Abraham Kusuma', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (854, 558, 'Abraham Kusuma +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (855, 559, 'Agus Kurniawan (Merry)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (856, 559, 'Agus Kurniawan (Merry) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (857, 562, 'Anita Yap', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (858, 563, 'Anto Wijaya', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (859, 563, 'Anto Wijaya +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (860, 564, 'Aubrey Julian', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (861, 564, 'Aubrey Julian +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (862, 564, 'Aubrey Julian +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (863, 565, 'Benjamin K. Tjahjono/Beben', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (864, 565, 'Benjamin K. Tjahjono/Beben +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (865, 566, 'Benjamin S. Tjendana', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (866, 566, 'Benjamin S. Tjendana +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (867, 567, 'Boediningsih (Acen)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (868, 568, 'Boediwati (Achin)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (869, 569, 'Carkam', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (870, 569, 'Carkam +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (871, 569, 'Carkam +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (872, 569, 'Carkam +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (873, 573, 'David Sukirman', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (874, 573, 'David Sukirman +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (875, 574, 'Demis and Falen', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (876, 574, 'Demis and Falen +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (877, 575, 'Dellya Gunawan', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (878, 576, 'Dikki Haryanto and Family', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (879, 576, 'Dikki Haryanto and Family +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (880, 576, 'Dikki Haryanto and Family +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (881, 577, 'Doddy and Family', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (882, 577, 'Doddy and Family +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (883, 577, 'Doddy and Family +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (884, 578, 'Donny Purba (Septin)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (885, 578, 'Donny Purba (Septin) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (886, 578, 'Donny Purba (Septin) +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (887, 579, 'Eddy Suwanto (Erna)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (888, 579, 'Eddy Suwanto (Erna) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (889, 581, 'Erik Ricardo', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (890, 582, 'Erwin Irawan', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (891, 582, 'Erwin Irawan +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (892, 583, 'Febbi Oktaviani', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (893, 587, 'Itha', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (894, 587, 'Itha +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (895, 587, 'Itha +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (896, 588, 'Jacob Soetiono', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (897, 588, 'Jacob Soetiono +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (902, 591, 'Kristian Yusak', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (903, 591, 'Kristian Yusak +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (904, 591, 'Kristian Yusak +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (905, 593, 'Lenawati S.', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (906, 594, 'Lie Sui Hin (Iing)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (907, 596, 'Mariana', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (908, 596, 'Mariana +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (909, 597, 'Maria Hadeli (Mintje)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (910, 598, 'Petrus (Maria Diardjo)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (911, 598, 'Petrus (Maria Diardjo) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (912, 599, 'Narto', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (913, 599, 'Narto +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (914, 599, 'Narto +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (915, 599, 'Narto +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (916, 601, 'Odang Hardjono', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (918, 602, 'Peter S. Tjendana', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (919, 602, 'Peter S. Tjendana +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (920, 606, 'Rudy Semarwan and Family', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (921, 606, 'Rudy Semarwan and Family +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (922, 607, 'Rusdyanto ', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (923, 607, 'Rusdyanto  +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (924, 609, 'Tatang Lie', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (925, 609, 'Tatang Lie +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (926, 610, 'Tinus Prasetio', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (927, 610, 'Tinus Prasetio +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (928, 615, 'Yapto Soetedjo and Family', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (929, 615, 'Yapto Soetedjo and Family +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (930, 615, 'Yapto Soetedjo and Family +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (931, 615, 'Yapto Soetedjo and Family +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (932, 619, 'Edi A. Frengky (Ester)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (933, 619, 'Edi A. Frengky (Ester) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (934, 619, 'Edi A. Frengky (Ester) +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (935, 619, 'Edi A. Frengky (Ester) +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (936, 620, 'Indriany', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (937, 621, 'Hankar A. Soemanto (Amel)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (938, 621, 'Hankar A. Soemanto (Amel) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (939, 621, 'Hankar A. Soemanto (Amel) +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (941, 622, 'Darwin Wijaya (Nini)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (942, 622, 'Darwin Wijaya (Nini) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (943, 622, 'Darwin Wijaya (Nini) +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (944, 624, 'Yosua', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (945, 624, 'Yosua +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (946, 626, 'Timothy Tirtanadi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (947, 628, 'Meidiana Tirtanadi', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (948, 629, 'Pdt. Jimmy Santo', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (949, 629, 'Pdt. Jimmy Santo +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (950, 630, 'Tjhin Sak Khie', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (953, 637, 'Evelyn Modesty', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (954, 637, 'Evelyn Modesty +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (956, 643, 'Pdt. Martin Harefa', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (957, 643, 'Pdt. Martin Harefa +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (962, 646, 'Pdt. Heru Tri Budi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (963, 646, 'Pdt. Heru Tri Budi +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (966, 649, 'Lucky Sunarjo', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (968, 650, 'Harijanto Tanoto', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (969, 650, 'Harijanto Tanoto +1', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (970, 651, 'Adven Christy (Marcilia)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (971, 652, 'Pdt. Samuel Sutjiono', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (972, 652, 'Pdt. Samuel Sutjiono +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (973, 653, 'Pdt. Benjamin Dharmajanto', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (975, 655, 'Hendra Sanusi (Litje)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (976, 655, 'Hendra Sanusi (Litje) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (977, 656, 'Distianto Suwito (Denny)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (979, 657, 'Djap Fatimah (Apian)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (981, 658, 'Haryanto (Annie)', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (982, 658, 'Haryanto (Annie) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (983, 661, 'Arif Santoso', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (984, 661, 'Arif Santoso +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (987, 663, 'Prisil and Hendi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (988, 663, 'Prisil and Hendi +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (989, 664, 'Cynthia Halim', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (990, 666, 'Jovan Raysano', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (991, 667, 'Gabriella Giovanny', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (992, 669, 'David Avila', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (993, 669, 'David Avila +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (994, 672, 'Stella Yohana', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (995, 672, 'Stella Yohana +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (996, 673, 'Jennie Wirawan', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (997, 675, 'Michelle Natalie', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (998, 675, 'Michelle Natalie +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1001, 680, 'Krisna Vieno', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1002, 684, 'Bryan Favian', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1003, 684, 'Bryan Favian +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1004, 685, 'Dieva Anandinata', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1005, 685, 'Dieva Anandinata +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1006, 687, 'Gevin Gunawan', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1007, 688, 'Reynaldo Domenico', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1008, 688, 'Reynaldo Domenico +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1009, 689, 'Devin Samuel', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1010, 689, 'Devin Samuel +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1011, 691, 'Reza Sjarfi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1012, 694, 'Nadia', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1013, 697, 'Rachel Lia', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1014, 697, 'Rachel Lia +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1015, 698, 'Stella Grace Timothy', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1016, 698, 'Stella Grace Timothy +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1017, 706, 'Sabrina', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1018, 706, 'Sabs dad', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1019, 706, 'Sabs mom', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1020, 706, 'Tata', 53, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1021, 707, 'Karel', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1022, 707, 'Papa', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1023, 707, 'Mama', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1024, 707, 'Klemens', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1025, 707, 'Eklesia', 56, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1026, 708, 'Hansel and Meidi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1027, 708, 'Hansel and Meidi +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1028, 710, 'Caroline and Tobias', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1029, 710, 'Caroline and Tobias +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1030, 713, 'Lina and Yana', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1031, 713, 'Lina and Yana +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1032, 723, 'Kurniawan Tanama', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1033, 723, 'Kurniawan Tanama +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1034, 724, 'Shan Khonada', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1035, 724, 'Shan Khonada +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1036, 725, 'Sheilla Khonada', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1037, 725, 'Sheilla Khonada +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1038, 726, 'Sheillya Khonada', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1039, 763, 'William', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1040, 763, 'William +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1041, 797, 'Tommy', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1042, 797, 'Tommy +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1043, 631, 'Irawaty Tjahyadi', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1044, 819, 'Teddy', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1045, 819, 'Teddy +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1046, 812, 'Eddy Tjung', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1049, 817, 'Andi +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1050, 827, 'Bun Haryati +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1051, 817, 'Andi +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1052, 833, 'Liu Lie Lie', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1053, 788, 'Phang Kim Liang', 55, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1054, 788, 'Phang Kim Liang +1', 55, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1058, 782, 'Fu Khong Hin dan keluarga', 55, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1059, 782, 'Fu Khong Hin dan keluarga +1', 55, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1060, 782, 'Fu Khong Hin dan keluarga +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1061, 782, 'Fu Khong Hin dan keluarga +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1062, 782, 'Fu Khong Hin dan keluarga +4', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1063, 834, 'Tan Lai Kim', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1064, 834, 'Tan Lai Kim +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1065, 835, 'Budi Dharmono', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1066, 835, 'Budi Dharmono +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1067, 836, 'Kho Siu Ngo', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1068, 836, 'Kho Siu Ngo +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1069, 837, 'Mui Lan', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1070, 838, 'Rosa', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1075, 842, 'Ivan Soedarto', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1076, 296, 'William R. Y.', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1077, 816, 'Neo Lenny +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1079, 840, 'Donny', 3, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1080, 656, 'Distianto Suwito (Denny) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1081, 590, 'Julianto', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1082, 590, 'Julianto +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1083, 590, 'Julianto +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1084, 843, 'Marsha and George', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1087, 845, 'Sui Cu', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1088, 601, 'Odang Hardjono +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1089, 825, 'Theresia L. (Nini) +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1090, 846, 'Henny Rachel', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1091, 505, 'Yohanes Nugroho +1', 32, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1095, 848, 'Lisa Wong', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1096, 848, 'Lisa Wong +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1097, 849, 'Nelly', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1098, 849, 'Nelly +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1099, 849, 'Nelly +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1100, 258, 'Thomas Kiangga', 11, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1103, 850, 'Jovan and Elaine', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1104, 850, 'Jovan and Elaine +1', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1108, 851, 'Jonathan Soekah', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1109, 851, 'Jonathan Soekah +1', 6, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1110, 258, 'Thomas Kiangga +1', 11, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1111, 493, 'Herman +6', 11, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1112, 374, 'Willy Ananta +2', 41, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1113, 374, 'Willy Ananta +3', 41, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1114, 375, 'Mario +2', 41, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1117, 852, 'Cindy', 1, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1118, 251, 'Jacklin Marselau +1', 11, 1);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1119, 630, 'Tjhin Sak Khie +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1122, 853, 'Kevin Wong', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1123, 853, 'Kevin Wong +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1124, 853, 'Kevin Wong +2', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1125, 853, 'Kevin Wong +3', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1126, 645, 'Pdt. Ridwan Hutabarat', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1127, 645, 'Pdt. Ridwan Hutabarat +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1128, 644, 'Pdt. Jimmy Kawilarang', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1129, 644, 'Pdt. Jimmy Kawilarang +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1130, 662, 'Husin', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1131, 662, 'Husin +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1132, 738, 'Anggi and Arief +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1133, 854, 'Siauw Njuk Khiun', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1134, 855, 'Tan Tin Nio', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1137, 844, 'Ina', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1138, 821, 'Suhendra +1', NULL, 0);
INSERT INTO guests (id, rsvp_id, name, table_id, checked_in) VALUES (1139, 792, 'Khou Sok Miang +1', NULL, 0);

-- Table: tables
INSERT INTO tables (id, name, max_guests, location) VALUES (1, '32.Trier/Sab', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (3, '31.Como3/Sab', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (6, '18.Como1/Sab', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (7, '17.Como2/Sab', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (8, '3.Berlin 2-family', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (10, 'VIP', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (11, '3A.Berlin 1-temen tata', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (13, '12A.Stockholm1-Blink2 Blitar', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (14, '1.Budapest2/Oma', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (15, '9.Budapest3/Oma', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (16, '10.Budapest4/Oma', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (17, '5.Oslo1-Weny', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (18, '11.Prague2/Opa', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (22, '15.Prague3/Opa', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (23, '16.Prague4/Opa', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (24, '27.Palma3/Tawon Rimba', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (25, '20.Bangkok1/Taman Agung', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (26, '24.Hallstatt1/Salah Gaul', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (27, '12.Prague1/Opa', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (28, '6.Oslo2-Weny', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (29, '7.Oslo3-Weny', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (30, '23.Hallstatt2/Salah Gaul', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (31, '25.Hallstatt3/Salah Gaul', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (32, '26.Hallstatt4/Salah Gaul', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (33, '19.Bangkok2/Taman Agung', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (34, '29.Bangkok3/Taman Agung', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (35, '30.Bangkok4/Taman Agung', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (36, '37.Dubrovnik3/Umum', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (37, '36.Rostock/Dempo Mami', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (39, '21.Palma2/Tawon Rimba', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (40, '22.Palma1/Tawon Rimba', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (41, '2.Budapest1/Oma', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (42, '28.Dubrovnik1/Umum', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (43, '8.Oslo4-Weny', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (45, '35.Split/Dempo Dad', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (47, '38.Dubrovnik2/Umum', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (48, '14.Stockholm2-Group Morodadi Blitar', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (52, 'Keluarga ama', 10, 'jakarta');
INSERT INTO tables (id, name, max_guests, location) VALUES (53, 'Sabs fam', 10, 'jakarta');
INSERT INTO tables (id, name, max_guests, location) VALUES (55, 'Keluarga Akong', 10, 'jakarta');
INSERT INTO tables (id, name, max_guests, location) VALUES (56, 'Keluarga Papa', 10, 'jakarta');
INSERT INTO tables (id, name, max_guests, location) VALUES (57, '33.', 10, 'malang');
INSERT INTO tables (id, name, max_guests, location) VALUES (58, '34.', 10, 'malang');

-- Table: groups
INSERT INTO groups (id, name) VALUES (1, 'Tata');
INSERT INTO groups (id, name) VALUES (4, 'Rena');
INSERT INTO groups (id, name) VALUES (46, 'Hadi');
INSERT INTO groups (id, name) VALUES (98, 'Weny');
INSERT INTO groups (id, name) VALUES (133, 'Blitar');
INSERT INTO groups (id, name) VALUES (152, 'Malang');
INSERT INTO groups (id, name) VALUES (180, 'Gaul');
INSERT INTO groups (id, name) VALUES (205, 'Umum');
INSERT INTO groups (id, name) VALUES (252, 'Karel');
INSERT INTO groups (id, name) VALUES (253, 'Mama');
INSERT INTO groups (id, name) VALUES (311, 'Papa');
INSERT INTO groups (id, name) VALUES (357, 'Cece');
INSERT INTO groups (id, name) VALUES (387, 'Sab');
INSERT INTO groups (id, name) VALUES (396, 'Industri');
