openapi: 3.0.0
info:
  title: Starting Section Content API
  version: 1.0.0
  description: API contract for managing starting section content in wedding configuration

paths:
  /api/wedding/config/starting-section:
    put:
      summary: Update starting section content
      description: Updates text content for the starting/hero section including names, parent info, and display toggles
      operationId: updateStartingSectionContent
      tags:
        - Starting Section
      security:
        - sessionCookie: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                groomName:
                  type: string
                  maxLength: 100
                  nullable: true
                  description: Groom's name for display (falls back to basic info if null)
                  example: 'John Doe'
                brideName:
                  type: string
                  maxLength: 100
                  nullable: true
                  description: Bride's name for display (falls back to basic info if null)
                  example: 'Jane Smith'
                showParentInfo:
                  type: boolean
                  description: Toggle to show/hide parent information
                  example: true
                groomFatherName:
                  type: string
                  maxLength: 100
                  nullable: true
                  description: "Groom's father name (X in 'Son of X and Y')"
                  example: 'Robert Doe'
                groomMotherName:
                  type: string
                  maxLength: 100
                  nullable: true
                  description: "Groom's mother name (Y in 'Son of X and Y')"
                  example: 'Mary Doe'
                brideFatherName:
                  type: string
                  maxLength: 100
                  nullable: true
                  description: "Bride's father name (Z in 'Daughter of Z and A')"
                  example: 'James Smith'
                brideMotherName:
                  type: string
                  maxLength: 100
                  nullable: true
                  description: "Bride's mother name (A in 'Daughter of Z and A')"
                  example: 'Patricia Smith'
                showWeddingDate:
                  type: boolean
                  description: Toggle to show/hide wedding date in starting section
                  example: true
              additionalProperties: false
            examples:
              fullUpdate:
                summary: Update all fields
                value:
                  groomName: 'John Doe'
                  brideName: 'Jane Smith'
                  showParentInfo: true
                  groomFatherName: 'Robert Doe'
                  groomMotherName: 'Mary Doe'
                  brideFatherName: 'James Smith'
                  brideMotherName: 'Patricia Smith'
                  showWeddingDate: true
              partialParentInfo:
                summary: Partial parent information (only groom's parents)
                value:
                  showParentInfo: true
                  groomFatherName: 'Robert Doe'
                  groomMotherName: 'Mary Doe'
                  brideFatherName: null
                  brideMotherName: null
              togglesOnly:
                summary: Update only toggles
                value:
                  showParentInfo: false
                  showWeddingDate: true
      responses:
        '200':
          description: Successfully updated starting section content
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/WeddingConfiguration'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                nameTooLong:
                  summary: Name exceeds maximum length
                  value:
                    success: false
                    error: 'groomName must be at most 100 characters'
                invalidType:
                  summary: Invalid field type
                  value:
                    success: false
                    error: 'showParentInfo must be a boolean'
        '401':
          description: Unauthorized - no valid session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: 'Unauthorized'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: 'Failed to update starting section content'

components:
  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: session
      description: Session-based authentication cookie

  schemas:
    WeddingConfiguration:
      type: object
      properties:
        id:
          type: string
          example: 'clx1234567890abcdefgh'
        userId:
          type: string
          example: 'user_clx9876543210zyxwvu'
        subdomain:
          type: string
          example: 'john-and-jane'
        groomName:
          type: string
          example: 'John Doe'
        brideName:
          type: string
          example: 'Jane Smith'
        weddingDate:
          type: string
          format: date-time
          example: '2025-06-15T00:00:00.000Z'
        startingSectionGroomName:
          type: string
          nullable: true
          example: 'John Doe'
        startingSectionBrideName:
          type: string
          nullable: true
          example: 'Jane Smith'
        startingSectionShowParentInfo:
          type: boolean
          example: true
        startingSectionGroomFatherName:
          type: string
          nullable: true
          example: 'Robert Doe'
        startingSectionGroomMotherName:
          type: string
          nullable: true
          example: 'Mary Doe'
        startingSectionBrideFatherName:
          type: string
          nullable: true
          example: 'James Smith'
        startingSectionBrideMotherName:
          type: string
          nullable: true
          example: 'Patricia Smith'
        startingSectionShowWeddingDate:
          type: boolean
          example: true
        startingSectionBackgroundType:
          type: string
          enum: [image, video]
          nullable: true
          example: 'image'
        startingSectionBackgroundFilename:
          type: string
          nullable: true
          example: 'background-image-1697654321.jpg'
        startingSectionBackgroundFileSize:
          type: integer
          nullable: true
          example: 2458624
        startingSectionBackgroundMimeType:
          type: string
          nullable: true
          example: 'image/jpeg'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: 'Error message'
      required:
        - success
        - error
